// Generated by the protocol buffer compiler.  DO NOT EDIT!
// clang-format off
// source: tokens.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30007
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30007 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - TokensRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface TokensRoot : GPBRootObject
@end

#pragma mark - TokenWrap

typedef GPB_ENUM(TokenWrap_FieldNumber) {
  TokenWrap_FieldNumber_AppKey = 1,
  TokenWrap_FieldNumber_Version = 2,
  TokenWrap_FieldNumber_TokenValue = 3,
};

GPB_FINAL @interface TokenWrap : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *appKey;

@property(nonatomic, readwrite) int32_t version;

@property(nonatomic, readwrite, copy, null_resettable) NSData *tokenValue;

@end

#pragma mark - TokenValue

typedef GPB_ENUM(TokenValue_FieldNumber) {
  TokenValue_FieldNumber_UserId = 1,
  TokenValue_FieldNumber_DeviceId = 2,
  TokenValue_FieldNumber_TokenTime = 3,
};

GPB_FINAL @interface TokenValue : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@property(nonatomic, readwrite) int64_t tokenTime;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)

// clang-format on
