// Generated by the protocol buffer compiler.  DO NOT EDIT!
// clang-format off
// source: appmessages.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30007
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30007 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Conversation;
@class DownMsg;
@class IndexScope;
@class MentionInfo;
@class MentionMsg;
@class PushData;
@class SimpleMsg;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum MentionType

typedef GPB_ENUM(MentionType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  MentionType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  MentionType_MentionDefault = 0,
  MentionType_MentionAll = 1,
  MentionType_MentionSomeone = 2,
  MentionType_MentionAllAndSomeone = 3,
};

GPBEnumDescriptor *MentionType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL MentionType_IsValidValue(int32_t value);

#pragma mark - Enum ChannelType

typedef GPB_ENUM(ChannelType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  ChannelType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  ChannelType_Unknown = 0,
  ChannelType_Private = 1,
  ChannelType_Group = 2,
  ChannelType_Chatroom = 3,
  ChannelType_System = 4,
};

GPBEnumDescriptor *ChannelType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL ChannelType_IsValidValue(int32_t value);

#pragma mark - Enum NotifyType

typedef GPB_ENUM(NotifyType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  NotifyType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  NotifyType_Default = 0,
  NotifyType_Msg = 1,
};

GPBEnumDescriptor *NotifyType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL NotifyType_IsValidValue(int32_t value);

#pragma mark - AppmessagesRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface AppmessagesRoot : GPBRootObject
@end

#pragma mark - UpMsg

typedef GPB_ENUM(UpMsg_FieldNumber) {
  UpMsg_FieldNumber_MsgType = 1,
  UpMsg_FieldNumber_MsgContent = 2,
  UpMsg_FieldNumber_Flags = 3,
  UpMsg_FieldNumber_ClientUid = 4,
  UpMsg_FieldNumber_PushData = 5,
  UpMsg_FieldNumber_MentionInfo = 6,
};

GPB_FINAL @interface UpMsg : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *msgType;

@property(nonatomic, readwrite, copy, null_resettable) NSData *msgContent;

@property(nonatomic, readwrite) int32_t flags;

@property(nonatomic, readwrite, copy, null_resettable) NSString *clientUid;

@property(nonatomic, readwrite, strong, null_resettable) PushData *pushData;
/** Test to see if @c pushData has been set. */
@property(nonatomic, readwrite) BOOL hasPushData;

@property(nonatomic, readwrite, strong, null_resettable) MentionInfo *mentionInfo;
/** Test to see if @c mentionInfo has been set. */
@property(nonatomic, readwrite) BOOL hasMentionInfo;

@end

#pragma mark - MentionInfo

typedef GPB_ENUM(MentionInfo_FieldNumber) {
  MentionInfo_FieldNumber_MentionType = 1,
  MentionInfo_FieldNumber_TargetIdsArray = 2,
};

GPB_FINAL @interface MentionInfo : GPBMessage

@property(nonatomic, readwrite) MentionType mentionType;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *targetIdsArray;
/** The number of items in @c targetIdsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger targetIdsArray_Count;

@end

/**
 * Fetches the raw value of a @c MentionInfo's @c mentionType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t MentionInfo_MentionType_RawValue(MentionInfo *message);
/**
 * Sets the raw value of an @c MentionInfo's @c mentionType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetMentionInfo_MentionType_RawValue(MentionInfo *message, int32_t value);

#pragma mark - PushData

typedef GPB_ENUM(PushData_FieldNumber) {
  PushData_FieldNumber_Title = 1,
  PushData_FieldNumber_PushId = 2,
  PushData_FieldNumber_PushText = 3,
  PushData_FieldNumber_PushExtraData = 4,
};

GPB_FINAL @interface PushData : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *title;

@property(nonatomic, readwrite, copy, null_resettable) NSString *pushId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *pushText;

@property(nonatomic, readwrite, copy, null_resettable) NSString *pushExtraData;

@end

#pragma mark - DownMsg

typedef GPB_ENUM(DownMsg_FieldNumber) {
  DownMsg_FieldNumber_TargetId = 1,
  DownMsg_FieldNumber_ChannelType = 2,
  DownMsg_FieldNumber_MsgType = 3,
  DownMsg_FieldNumber_SenderId = 4,
  DownMsg_FieldNumber_MsgId = 5,
  DownMsg_FieldNumber_MsgIndex = 6,
  DownMsg_FieldNumber_MsgContent = 7,
  DownMsg_FieldNumber_MsgTime = 8,
  DownMsg_FieldNumber_Flags = 9,
  DownMsg_FieldNumber_IsSend = 10,
  DownMsg_FieldNumber_Platform = 11,
  DownMsg_FieldNumber_ClientUid = 12,
  DownMsg_FieldNumber_PushData = 13,
  DownMsg_FieldNumber_MentionInfo = 14,
  DownMsg_FieldNumber_IsReaded = 15,
};

GPB_FINAL @interface DownMsg : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *targetId;

@property(nonatomic, readwrite) ChannelType channelType;

@property(nonatomic, readwrite, copy, null_resettable) NSString *msgType;

@property(nonatomic, readwrite, copy, null_resettable) NSString *senderId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *msgId;

@property(nonatomic, readwrite) int64_t msgIndex;

@property(nonatomic, readwrite, copy, null_resettable) NSData *msgContent;

@property(nonatomic, readwrite) int64_t msgTime;

@property(nonatomic, readwrite) int32_t flags;

@property(nonatomic, readwrite) BOOL isSend;

@property(nonatomic, readwrite, copy, null_resettable) NSString *platform;

@property(nonatomic, readwrite, copy, null_resettable) NSString *clientUid;

@property(nonatomic, readwrite, strong, null_resettable) PushData *pushData;
/** Test to see if @c pushData has been set. */
@property(nonatomic, readwrite) BOOL hasPushData;

@property(nonatomic, readwrite, strong, null_resettable) MentionInfo *mentionInfo;
/** Test to see if @c mentionInfo has been set. */
@property(nonatomic, readwrite) BOOL hasMentionInfo;

@property(nonatomic, readwrite) BOOL isReaded;

@end

/**
 * Fetches the raw value of a @c DownMsg's @c channelType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t DownMsg_ChannelType_RawValue(DownMsg *message);
/**
 * Sets the raw value of an @c DownMsg's @c channelType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetDownMsg_ChannelType_RawValue(DownMsg *message, int32_t value);

#pragma mark - Notify

typedef GPB_ENUM(Notify_FieldNumber) {
  Notify_FieldNumber_Type = 1,
  Notify_FieldNumber_SyncTime = 2,
};

GPB_FINAL @interface Notify : GPBMessage

@property(nonatomic, readwrite) NotifyType type;

@property(nonatomic, readwrite) int64_t syncTime;

@end

/**
 * Fetches the raw value of a @c Notify's @c type property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t Notify_Type_RawValue(Notify *message);
/**
 * Sets the raw value of an @c Notify's @c type property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetNotify_Type_RawValue(Notify *message, int32_t value);

#pragma mark - SyncMsgReq

typedef GPB_ENUM(SyncMsgReq_FieldNumber) {
  SyncMsgReq_FieldNumber_SyncTime = 1,
  SyncMsgReq_FieldNumber_ContainsSendBox = 2,
  SyncMsgReq_FieldNumber_SendBoxSyncTime = 3,
};

GPB_FINAL @interface SyncMsgReq : GPBMessage

/** 收件箱同步时间 */
@property(nonatomic, readwrite) int64_t syncTime;

/** 是否包含发件箱消息 */
@property(nonatomic, readwrite) BOOL containsSendBox;

/** 发件箱同步时间 */
@property(nonatomic, readwrite) int64_t sendBoxSyncTime;

@end

#pragma mark - DownMsgSet

typedef GPB_ENUM(DownMsgSet_FieldNumber) {
  DownMsgSet_FieldNumber_MsgsArray = 1,
  DownMsgSet_FieldNumber_SyncTime = 2,
  DownMsgSet_FieldNumber_IsFinished = 3,
};

GPB_FINAL @interface DownMsgSet : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<DownMsg*> *msgsArray;
/** The number of items in @c msgsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger msgsArray_Count;

@property(nonatomic, readwrite) int64_t syncTime;

@property(nonatomic, readwrite) BOOL isFinished;

@end

#pragma mark - AddHisMsgReq

typedef GPB_ENUM(AddHisMsgReq_FieldNumber) {
  AddHisMsgReq_FieldNumber_SenderId = 1,
  AddHisMsgReq_FieldNumber_TargetId = 2,
  AddHisMsgReq_FieldNumber_ChannelType = 3,
  AddHisMsgReq_FieldNumber_SendTime = 4,
  AddHisMsgReq_FieldNumber_Msg = 5,
};

GPB_FINAL @interface AddHisMsgReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *senderId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *targetId;

@property(nonatomic, readwrite) ChannelType channelType;

@property(nonatomic, readwrite) int64_t sendTime;

@property(nonatomic, readwrite, strong, null_resettable) DownMsg *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

@end

/**
 * Fetches the raw value of a @c AddHisMsgReq's @c channelType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t AddHisMsgReq_ChannelType_RawValue(AddHisMsgReq *message);
/**
 * Sets the raw value of an @c AddHisMsgReq's @c channelType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetAddHisMsgReq_ChannelType_RawValue(AddHisMsgReq *message, int32_t value);

#pragma mark - QryMsgLatestIndexReq

typedef GPB_ENUM(QryMsgLatestIndexReq_FieldNumber) {
  QryMsgLatestIndexReq_FieldNumber_ConverId = 1,
  QryMsgLatestIndexReq_FieldNumber_ChannelType = 2,
};

GPB_FINAL @interface QryMsgLatestIndexReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *converId;

@property(nonatomic, readwrite) ChannelType channelType;

@end

/**
 * Fetches the raw value of a @c QryMsgLatestIndexReq's @c channelType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t QryMsgLatestIndexReq_ChannelType_RawValue(QryMsgLatestIndexReq *message);
/**
 * Sets the raw value of an @c QryMsgLatestIndexReq's @c channelType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetQryMsgLatestIndexReq_ChannelType_RawValue(QryMsgLatestIndexReq *message, int32_t value);

#pragma mark - QryMsgLatestIndexResp

typedef GPB_ENUM(QryMsgLatestIndexResp_FieldNumber) {
  QryMsgLatestIndexResp_FieldNumber_ConverId = 1,
  QryMsgLatestIndexResp_FieldNumber_ChannelType = 2,
  QryMsgLatestIndexResp_FieldNumber_MsgIndex = 3,
};

GPB_FINAL @interface QryMsgLatestIndexResp : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *converId;

@property(nonatomic, readwrite) ChannelType channelType;

@property(nonatomic, readwrite) int64_t msgIndex;

@end

/**
 * Fetches the raw value of a @c QryMsgLatestIndexResp's @c channelType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t QryMsgLatestIndexResp_ChannelType_RawValue(QryMsgLatestIndexResp *message);
/**
 * Sets the raw value of an @c QryMsgLatestIndexResp's @c channelType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetQryMsgLatestIndexResp_ChannelType_RawValue(QryMsgLatestIndexResp *message, int32_t value);

#pragma mark - QryHisMsgsReq

typedef GPB_ENUM(QryHisMsgsReq_FieldNumber) {
  QryHisMsgsReq_FieldNumber_TargetId = 1,
  QryHisMsgsReq_FieldNumber_ChannelType = 2,
  QryHisMsgsReq_FieldNumber_StartTime = 3,
  QryHisMsgsReq_FieldNumber_Count = 4,
  QryHisMsgsReq_FieldNumber_Order = 5,
};

GPB_FINAL @interface QryHisMsgsReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *targetId;

@property(nonatomic, readwrite) ChannelType channelType;

@property(nonatomic, readwrite) int64_t startTime;

@property(nonatomic, readwrite) int32_t count;

@property(nonatomic, readwrite) int32_t order;

@end

/**
 * Fetches the raw value of a @c QryHisMsgsReq's @c channelType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t QryHisMsgsReq_ChannelType_RawValue(QryHisMsgsReq *message);
/**
 * Sets the raw value of an @c QryHisMsgsReq's @c channelType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetQryHisMsgsReq_ChannelType_RawValue(QryHisMsgsReq *message, int32_t value);

#pragma mark - QryConversationsReq

typedef GPB_ENUM(QryConversationsReq_FieldNumber) {
  QryConversationsReq_FieldNumber_StartTime = 1,
  QryConversationsReq_FieldNumber_Count = 2,
  QryConversationsReq_FieldNumber_Order = 3,
};

GPB_FINAL @interface QryConversationsReq : GPBMessage

@property(nonatomic, readwrite) int64_t startTime;

@property(nonatomic, readwrite) int32_t count;

@property(nonatomic, readwrite) int32_t order;

@end

#pragma mark - QryConversationsResp

typedef GPB_ENUM(QryConversationsResp_FieldNumber) {
  QryConversationsResp_FieldNumber_ConversationsArray = 1,
  QryConversationsResp_FieldNumber_IsFinished = 2,
};

GPB_FINAL @interface QryConversationsResp : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Conversation*> *conversationsArray;
/** The number of items in @c conversationsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger conversationsArray_Count;

@property(nonatomic, readwrite) BOOL isFinished;

@end

#pragma mark - Conversation

typedef GPB_ENUM(Conversation_FieldNumber) {
  Conversation_FieldNumber_TargetId = 2,
  Conversation_FieldNumber_ChannelType = 3,
  Conversation_FieldNumber_UpdateTime = 4,
  Conversation_FieldNumber_UnreadCount = 5,
  Conversation_FieldNumber_Msg = 6,
  Conversation_FieldNumber_LatestReadedMsgIndex = 7,
  Conversation_FieldNumber_LatestMentionMsg = 8,
};

GPB_FINAL @interface Conversation : GPBMessage

/** string converId = 1; */
@property(nonatomic, readwrite, copy, null_resettable) NSString *targetId;

@property(nonatomic, readwrite) ChannelType channelType;

@property(nonatomic, readwrite) int64_t updateTime;

@property(nonatomic, readwrite) int64_t unreadCount;

@property(nonatomic, readwrite, strong, null_resettable) DownMsg *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

@property(nonatomic, readwrite) int64_t latestReadedMsgIndex;

@property(nonatomic, readwrite, strong, null_resettable) MentionMsg *latestMentionMsg;
/** Test to see if @c latestMentionMsg has been set. */
@property(nonatomic, readwrite) BOOL hasLatestMentionMsg;

@end

/**
 * Fetches the raw value of a @c Conversation's @c channelType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t Conversation_ChannelType_RawValue(Conversation *message);
/**
 * Sets the raw value of an @c Conversation's @c channelType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetConversation_ChannelType_RawValue(Conversation *message, int32_t value);

#pragma mark - MentionMsg

typedef GPB_ENUM(MentionMsg_FieldNumber) {
  MentionMsg_FieldNumber_MentionType = 1,
  MentionMsg_FieldNumber_SenderId = 2,
  MentionMsg_FieldNumber_MsgId = 3,
  MentionMsg_FieldNumber_MsgIndex = 4,
  MentionMsg_FieldNumber_MsgTime = 5,
};

GPB_FINAL @interface MentionMsg : GPBMessage

@property(nonatomic, readwrite) MentionType mentionType;

@property(nonatomic, readwrite, copy, null_resettable) NSString *senderId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *msgId;

@property(nonatomic, readwrite) int64_t msgIndex;

@property(nonatomic, readwrite) int64_t msgTime;

@end

/**
 * Fetches the raw value of a @c MentionMsg's @c mentionType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t MentionMsg_MentionType_RawValue(MentionMsg *message);
/**
 * Sets the raw value of an @c MentionMsg's @c mentionType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetMentionMsg_MentionType_RawValue(MentionMsg *message, int32_t value);

#pragma mark - QryMentionMsgsReq

typedef GPB_ENUM(QryMentionMsgsReq_FieldNumber) {
  QryMentionMsgsReq_FieldNumber_TargetId = 1,
  QryMentionMsgsReq_FieldNumber_ChannelType = 2,
  QryMentionMsgsReq_FieldNumber_StartIndex = 3,
  QryMentionMsgsReq_FieldNumber_Count = 4,
  QryMentionMsgsReq_FieldNumber_Order = 5,
};

GPB_FINAL @interface QryMentionMsgsReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *targetId;

@property(nonatomic, readwrite) ChannelType channelType;

@property(nonatomic, readwrite) int64_t startIndex;

@property(nonatomic, readwrite) int32_t count;

@property(nonatomic, readwrite) int32_t order;

@end

/**
 * Fetches the raw value of a @c QryMentionMsgsReq's @c channelType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t QryMentionMsgsReq_ChannelType_RawValue(QryMentionMsgsReq *message);
/**
 * Sets the raw value of an @c QryMentionMsgsReq's @c channelType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetQryMentionMsgsReq_ChannelType_RawValue(QryMentionMsgsReq *message, int32_t value);

#pragma mark - QryMentionMsgsResp

typedef GPB_ENUM(QryMentionMsgsResp_FieldNumber) {
  QryMentionMsgsResp_FieldNumber_MentionMsgsArray = 1,
  QryMentionMsgsResp_FieldNumber_IsFinished = 2,
};

GPB_FINAL @interface QryMentionMsgsResp : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<MentionMsg*> *mentionMsgsArray;
/** The number of items in @c mentionMsgsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger mentionMsgsArray_Count;

@property(nonatomic, readwrite) BOOL isFinished;

@end

#pragma mark - SyncConversationsReq

typedef GPB_ENUM(SyncConversationsReq_FieldNumber) {
  SyncConversationsReq_FieldNumber_StartTime = 1,
  SyncConversationsReq_FieldNumber_Count = 2,
};

GPB_FINAL @interface SyncConversationsReq : GPBMessage

@property(nonatomic, readwrite) int64_t startTime;

@property(nonatomic, readwrite) int32_t count;

@end

#pragma mark - DelConversationReq

typedef GPB_ENUM(DelConversationReq_FieldNumber) {
  DelConversationReq_FieldNumber_ConversationsArray = 1,
};

GPB_FINAL @interface DelConversationReq : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Conversation*> *conversationsArray;
/** The number of items in @c conversationsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger conversationsArray_Count;

@end

#pragma mark - ClearUnreadReq

typedef GPB_ENUM(ClearUnreadReq_FieldNumber) {
  ClearUnreadReq_FieldNumber_ConversationsArray = 1,
};

GPB_FINAL @interface ClearUnreadReq : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Conversation*> *conversationsArray;
/** The number of items in @c conversationsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger conversationsArray_Count;

@end

#pragma mark - RecallMsgReq

typedef GPB_ENUM(RecallMsgReq_FieldNumber) {
  RecallMsgReq_FieldNumber_TargetId = 1,
  RecallMsgReq_FieldNumber_ChannelType = 2,
  RecallMsgReq_FieldNumber_MsgId = 3,
  RecallMsgReq_FieldNumber_MsgTime = 4,
  RecallMsgReq_FieldNumber_MsgType = 5,
  RecallMsgReq_FieldNumber_MsgContent = 6,
};

GPB_FINAL @interface RecallMsgReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *targetId;

@property(nonatomic, readwrite) ChannelType channelType;

@property(nonatomic, readwrite, copy, null_resettable) NSString *msgId;

@property(nonatomic, readwrite) int64_t msgTime;

@property(nonatomic, readwrite, copy, null_resettable) NSString *msgType;

@property(nonatomic, readwrite, copy, null_resettable) NSData *msgContent;

@end

/**
 * Fetches the raw value of a @c RecallMsgReq's @c channelType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t RecallMsgReq_ChannelType_RawValue(RecallMsgReq *message);
/**
 * Sets the raw value of an @c RecallMsgReq's @c channelType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetRecallMsgReq_ChannelType_RawValue(RecallMsgReq *message, int32_t value);

#pragma mark - MarkReadReq

typedef GPB_ENUM(MarkReadReq_FieldNumber) {
  MarkReadReq_FieldNumber_TargetId = 1,
  MarkReadReq_FieldNumber_ChannelType = 2,
  MarkReadReq_FieldNumber_MsgsArray = 3,
  MarkReadReq_FieldNumber_IndexScopesArray = 4,
};

GPB_FINAL @interface MarkReadReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *targetId;

@property(nonatomic, readwrite) ChannelType channelType;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<SimpleMsg*> *msgsArray;
/** The number of items in @c msgsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger msgsArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<IndexScope*> *indexScopesArray;
/** The number of items in @c indexScopesArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger indexScopesArray_Count;

@end

/**
 * Fetches the raw value of a @c MarkReadReq's @c channelType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t MarkReadReq_ChannelType_RawValue(MarkReadReq *message);
/**
 * Sets the raw value of an @c MarkReadReq's @c channelType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetMarkReadReq_ChannelType_RawValue(MarkReadReq *message, int32_t value);

#pragma mark - SimpleMsg

typedef GPB_ENUM(SimpleMsg_FieldNumber) {
  SimpleMsg_FieldNumber_MsgId = 1,
  SimpleMsg_FieldNumber_MsgTime = 2,
  SimpleMsg_FieldNumber_MsgIndex = 3,
};

GPB_FINAL @interface SimpleMsg : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *msgId;

@property(nonatomic, readwrite) int64_t msgTime;

@property(nonatomic, readwrite) int64_t msgIndex;

@end

#pragma mark - IndexScope

typedef GPB_ENUM(IndexScope_FieldNumber) {
  IndexScope_FieldNumber_StartIndex = 1,
  IndexScope_FieldNumber_EndIndex = 2,
};

GPB_FINAL @interface IndexScope : GPBMessage

@property(nonatomic, readwrite) int64_t startIndex;

@property(nonatomic, readwrite) int64_t endIndex;

@end

#pragma mark - ModifyMsgReq

typedef GPB_ENUM(ModifyMsgReq_FieldNumber) {
  ModifyMsgReq_FieldNumber_TargetId = 1,
  ModifyMsgReq_FieldNumber_ChannelType = 2,
  ModifyMsgReq_FieldNumber_MsgId = 3,
  ModifyMsgReq_FieldNumber_MsgTime = 4,
  ModifyMsgReq_FieldNumber_MsgIndex = 5,
  ModifyMsgReq_FieldNumber_MsgContent = 6,
};

GPB_FINAL @interface ModifyMsgReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *targetId;

@property(nonatomic, readwrite) ChannelType channelType;

@property(nonatomic, readwrite, copy, null_resettable) NSString *msgId;

@property(nonatomic, readwrite) int64_t msgTime;

@property(nonatomic, readwrite) int64_t msgIndex;

@property(nonatomic, readwrite, copy, null_resettable) NSData *msgContent;

@end

/**
 * Fetches the raw value of a @c ModifyMsgReq's @c channelType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t ModifyMsgReq_ChannelType_RawValue(ModifyMsgReq *message);
/**
 * Sets the raw value of an @c ModifyMsgReq's @c channelType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetModifyMsgReq_ChannelType_RawValue(ModifyMsgReq *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)

// clang-format on
