# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
            end
        end
    end
end

target 'QuickStart' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QuickStart
  pod 'MBProgressHUD', '1.1.0'
  pod 'Masonry', '1.1.0'
  pod 'SDWebImage', '5.20.0'
  pod 'LiveKitClient', '2.0.18'
  pod 'ShengwangRtcEngine_iOS', '4.6.0'

end
