// Generated by the protocol buffer compiler.  DO NOT EDIT!
// clang-format off
// source: innermessages.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30007
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30007 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - InnermessagesRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface InnermessagesRoot : GPBRootObject
@end

#pragma mark - UserRegReq

typedef GPB_ENUM(UserRegReq_FieldNumber) {
  UserRegReq_FieldNumber_UserId = 1,
  UserRegReq_FieldNumber_Nickname = 2,
  UserRegReq_FieldNumber_UserPortrait = 3,
};

GPB_FINAL @interface UserRegReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *nickname;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userPortrait;

@end

#pragma mark - UserReqResp

typedef GPB_ENUM(UserReqResp_FieldNumber) {
  UserReqResp_FieldNumber_UserId = 1,
  UserReqResp_FieldNumber_Token = 2,
};

GPB_FINAL @interface UserReqResp : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *token;

@end

#pragma mark - GroupAddMembersReq

typedef GPB_ENUM(GroupAddMembersReq_FieldNumber) {
  GroupAddMembersReq_FieldNumber_GroupId = 1,
  GroupAddMembersReq_FieldNumber_GroupName = 2,
  GroupAddMembersReq_FieldNumber_MemberIdsArray = 3,
};

GPB_FINAL @interface GroupAddMembersReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *groupName;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *memberIdsArray;
/** The number of items in @c memberIdsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger memberIdsArray_Count;

@end

#pragma mark - GroupAddMembersResp

GPB_FINAL @interface GroupAddMembersResp : GPBMessage

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)

// clang-format on
